server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.199:3306/springCloudProject?useSSL=false&useUnicode=true&chracterEncoding=utf-8
    username: root
    password: hong123

eureka:
  client:
    #是否将自己注册金Eureka Server
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #注册中心集群时，用逗号分隔
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.leeon.springcloud.entities

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream